server:
  port: 9102
spring:
  kafka:
    bootstrap-servers: 118.89.19.254:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer